INSERT INTO burgers (burgerName, devoured) VALUES ("House Special", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Rodeo Rage", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Mushroom Madness", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Montezuma's Revenge", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Round Table", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Highrise", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Towering Inferno", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Blue Moon", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Where's The Beef", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Yesterday's Trash", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Frontal Lobotomy", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("What's In This", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Bring More Napkins", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("The Meatless Disappointment", FALSE);
INSERT INTO burgers (burgerName, devoured) VALUES ("Call In Sick Tomorrow", FALSE);